### ISSUE TITLE
streamlit button not clickable

### ISSUE THREAD

**Issue by shorpenlee** [streamlit-community/streamlit-navigation-bar#11]
### Checklist

- [X] I have searched the [existing issues](https://github.com/gabrieltempass/streamlit-navigation-bar/issues) for similar issues.
- [X] I added a very descriptive title to this issue.
- [X] I have provided sufficient information below to help reproduce this issue.

### Summary

The Streamlit button is not clickable when using streamlit-community-navigation-bar-4.0.6. Additionally, the newly released streamlit-community-navigation-bar-4.0.7 has a bug where all pages are not visible.

4.0.6:
![image](https://github.com/user-attachments/assets/28117c10-4628-4a5f-910e-b17cd5233a8a)
4.0.7:
![image](https://github.com/user-attachments/assets/444195bf-7375-45fc-9b93-8d3f26066059)

### Reproducible code example

```Python
import streamlit as st
from streamlit_navigation_bar import st_navbar
import pages as pg


pages = ["Home", "Data Explorer", "Contact", "Test"]
parent_dir = os.path.dirname(os.path.abspath(__file__))

options = {
    "show_menu": False,
    "show_sidebar": False,
}

page = st_navbar(
    pages,
#    logo_path=logo_path,
#    urls=urls,
#    styles=styles,
    options=options,
)

functions = {
    "Home": pg.show_home,
    "Home": pg.show_home,
    "Data Explorer": pg.show_user_guide,
    "Contact": pg.show_api,
     "Test": pg.show_api
}

def on_button_click():
    st.session_state.button_clicked = True



if 'button_clicked' not in st.session_state:
    st.session_state.button_clicked = False

if st.button('Click me', on_click=on_button_click):
    st.write('Button clicked!')

go_to = functions.get(page)
if go_to:
    go_to()
```

### Is this a regression?

- [ ] Yes, this used to work in a previous version.

### Debug info

- Streamlit version:
- Streamlit Navigation Bar version:
- Python version:
- Operating System:
- Browser:

**Comment by shorpenlee** [comment]
error message of version 4.0.7 in terminal is: 

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xxxxx\\Anaconda3\\envs\\xxxxx\\Lib\\site-packages\\streamlit_navigation_bar\\frontend\\dist\\index.html'

**Comment by hansthen** [comment]
Something went wrong creating release 4.0.7. I just uploaded created a new version (4.0.9). This should both avoid this error and the fact that main streamlit elements do not receive pointer events.

Can you try that and see if it solves your issue?
