### ISSUE TITLE
Error loading component

### ISSUE THREAD

**Issue by JungeAlexander** [streamlit-community/streamlit-navigation-bar#2]
### Checklist

- [X] I have read the documentation at the [Wiki](https://github.com/gabrieltempass/streamlit-navigation-bar/wiki/API-reference).

### Description

Thanks for this! When trying to switch from streamlit-navigation-bar to here, I see the following error:

```
Your app is having trouble loading the streamlit_navigation_bar.st_navbar component. The app is attempting to load the component from http://localhost:5173/, and hasn't received its Streamlit.setComponentReady() message.

If this is a development build, have you started the dev server?

For more troubleshooting help, please see the [Streamlit Component docs](https://docs.streamlit.io/develop/concepts/custom-components) or visit our [forums](https://discuss.streamlit.io/).
```

Any idea what might be going wrong?

**Comment by hansthen** [comment]
How did you install the component? Did you use the pip version or the one from the repository?

**Comment by JungeAlexander** [comment]
Thanks! I did install it from pypi.

**Comment by hansthen** [comment]
I think I found the cause of this specific issue, but it will take me some time to properly fix. There are some other issues with streamlit-1.39.0. 

I will rollout a new version that will work with streamlit-1.38.0 soon.

**Comment by hansthen** [comment]
I published a version that will work with streamlit 1.38. I will check the other issues with 1.39 later.

**Comment by hansthen** [comment]
I just published a package that should work again with later versions of streamlit.
