### ISSUE TITLE
Wrong installation instructions

### ISSUE THREAD

**Issue by Leon0402** [streamlit-community/streamlit-navigation-bar#6]
### Checklist

- [X] I have searched the [existing issues](https://github.com/gabrieltempass/streamlit-navigation-bar/issues) for similar issues.
- [X] I added a very descriptive title to this issue.
- [X] I have provided sufficient information below to help reproduce this issue.

### Summary

The correct installation instructions should be: 
```
pip install streamlit-community-navigation-bar
```

The old package name is still mentioned in the readme

### Is this a regression?

- [ ] Yes, this used to work in a previous version.

### Debug info

- Streamlit version:
- Streamlit Navigation Bar version:
- Python version:
- Operating System:
- Browser:

**Comment by hansthen** [comment]
Good catch . . .
