### ISSUE TITLE
st.chat_input not responsive

### ISSUE THREAD

**Issue by tattrongvu** [streamlit-community/streamlit-navigation-bar#8]
### Checklist

- [X] I have searched the [existing issues](https://github.com/gabrieltempass/streamlit-navigation-bar/issues) for similar issues.
- [X] I added a very descriptive title to this issue.
- [X] I have provided sufficient information below to help reproduce this issue.

### Summary

Hi, thanks very much for your package.
After upgrade the streamlit from 1.36.0 to 1.39.0 or later as follow:
```
streamlit==1.39.0 #was 1.36.0
#streamlit-navigation-bar==3.3.0
streamlit-community-navigation-bar==4.0.4
```
Somehow the st.chat_input doesn't work anymore, bellow is the minimal code to reproduce:
```
import streamlit as st
from streamlit_navigation_bar import st_navbar

page = st_navbar(["Home", "Documentation", "Examples", "Community", "About"])
st.write(page)

if page=="Home":
    prompt = st.chat_input("Say something")
    if prompt:
        st.write(f"User has sent the following prompt: {prompt}")
```
The chat_input is freeze and I can not type anything into it. But the page is still responsive, I can still switch the navbar.
Downgrade streamlit to bellow 1.39.0 work as normal.
It currently block my task.
Any help appreciated. 

### Is this a regression?

- [ ] Yes, this used to work in a previous version.

### Debug info

- Streamlit version:
- Streamlit Navigation Bar version:
- Python version:
- Operating System:
- Browser:

**Comment by hansthen** [comment]
Have a look at version 4.0.6. This should fix the issue.

**Comment by tattrongvu** [comment]
thank you so much :), it worked.

**Comment by tattrongvu** [comment]
solved by: pip install streamlit-community-navigation-bar==4.0.6

**Comment by tattrongvu** [comment]
solved by: pip install streamlit-community-navigation-bar==4.0.6
